# frontend/utils/html_report.py
"""HTML and JUnit report builders for test suite results."""


def build_html_report(suite_result: dict) -> str:
    """Generate a styled HTML test report from a suite result dict."""
    from jinja2 import Environment

    template_str = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>{{ suite_name }} - Test Report</title>
<style>
  body{font-family:Arial,sans-serif;margin:32px;color:#333}
  h1{color:#1f77b4}
  .badge{padding:4px 14px;border-radius:4px;font-weight:bold;color:#fff}
  .pass{background:#28a745}.fail{background:#dc3545}
  table{border-collapse:collapse;width:100%;margin-top:24px}
  th{background:#f5f5f5;padding:10px 8px;text-align:left;border-bottom:2px solid #ddd;font-size:.9em}
  td{padding:8px;border-bottom:1px solid #eee;font-size:.88em}
  tr.pass-row td:first-child{color:#28a745;font-weight:bold}
  tr.fail-row td:first-child{color:#dc3545;font-weight:bold}
  .meta{color:#666;font-size:.9em;margin:12px 0}
</style></head><body>
<h1>{{ suite_name }}</h1>
<p class="meta">
  Run: <b>{{ run_at }}</b> &nbsp;|&nbsp; {{ passed }}/{{ total }} passed
  &nbsp;|&nbsp; {{ duration_ms }} ms &nbsp;
  <span class="badge {{ 'pass' if passed == total else 'fail' }}">
    {{ 'ALL PASS' if passed == total else 'HAS FAILURES' }}
  </span>
</p>
<table>
<tr><th>Result</th><th>Scenario</th><th>Exp RC</th><th>Act RC</th>
    <th>Exp Decision</th><th>Act Decision</th><th>ms</th></tr>
{% for r in results %}
<tr class="{{ 'pass-row' if r.passed else 'fail-row' }}">
  <td>{{ '✅ PASS' if r.passed else '❌ FAIL' }}</td>
  <td>{{ r.name }}</td>
  <td>{{ r.expected_network_response_code }}</td>
  <td>{{ r.actual_network_response_code }}</td>
  <td>{{ r.expected_customer_decision }}</td>
  <td>{{ r.actual_customer_decision }}</td>
  <td>{{ r.duration_ms }}</td>
</tr>
{% endfor %}
</table>
<p style="color:#aaa;font-size:.8em;margin-top:32px">
  Generated by Paycon e2ePS
</p>
</body></html>"""
    return Environment().from_string(template_str).render(**suite_result)


def build_junit_xml(suite_result: dict) -> str:
    """Generate JUnit XML from a suite result dict (for CI pipelines)."""
    results = suite_result.get("results", [])
    total = suite_result.get("total", len(results))
    failures = suite_result.get("failed", 0)
    duration_s = round((suite_result.get("duration_ms") or 0) / 1000, 3)
    suite_name = suite_result.get("suite_name", "Marqeta Suite")

    cases = []
    for r in results:
        name = r.get("name", r.get("scenario_id", "unknown"))
        t = round((r.get("duration_ms") or 0) / 1000, 3)
        case = f'    <testcase name="{_esc(name)}" classname="{_esc(suite_name)}" time="{t}">'
        if not r.get("passed"):
            exp_rc = r.get("expected_network_response_code", "?")
            act_rc = r.get("actual_network_response_code", "?")
            exp_d = r.get("expected_customer_decision", "?")
            act_d = r.get("actual_customer_decision", "?")
            msg = f"RC expected={exp_rc} actual={act_rc}; Decision expected={exp_d} actual={act_d}"
            case += (
                f'\n      <failure message="{_esc(msg)}">'
                f"{_esc(msg)}"
                f"</failure>\n    "
            )
        case += "</testcase>"
        cases.append(case)

    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        f'<testsuites name="{_esc(suite_name)}" tests="{total}" '
        f'failures="{failures}" time="{duration_s}">\n'
        f'  <testsuite name="{_esc(suite_name)}" tests="{total}" '
        f'failures="{failures}" time="{duration_s}">\n'
        + "\n".join(cases)
        + "\n  </testsuite>\n</testsuites>"
    )


def build_certification_report(certify_result: dict) -> str:
    """Generate a branded Paycon JIT Certification HTML report.

    Args:
        certify_result: dict returned by POST /certify.

    Returns:
        Self-contained HTML string suitable for download or PDF export.
    """
    from jinja2 import Environment

    # Jinja2 doesn't like raw {% %} inside string — use raw block
    template_str = r"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Paycon e2ePS — JIT Certification Report</title>
<style>
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:Arial,sans-serif;background:#f0f4f8;color:#1a2233;padding:0}
  .page{max-width:920px;margin:0 auto;background:#fff;padding:40px 48px 56px;
        box-shadow:0 2px 16px #0002}
  .header{display:flex;align-items:center;justify-content:space-between;
          border-bottom:3px solid #1fb7ac;padding-bottom:20px;margin-bottom:28px}
  .brand{font-size:1.5em;font-weight:800;color:#0a1730;letter-spacing:-.02em}
  .brand span{color:#1fb7ac}
  .report-title{font-size:.9em;color:#5a7a9a;margin-top:4px}
  .verdict{text-align:center;padding:18px 0;border-radius:8px;margin-bottom:28px;
           font-size:1.4em;font-weight:700;color:#fff}
  .cert-yes{background:linear-gradient(135deg,#1fb7ac,#2ecc71)}
  .cert-no{background:linear-gradient(135deg,#e74c3c,#f39c12)}
  .meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px 32px;
             margin-bottom:28px;font-size:.92em}
  .lbl{color:#7a9cc0;font-size:.78em;text-transform:uppercase;letter-spacing:.06em}
  .val{font-weight:600;color:#1a2233;margin-top:2px;word-break:break-all}
  .scorecard{display:flex;gap:16px;margin-bottom:28px}
  .sc{flex:1;background:#f4f8fc;border-radius:8px;padding:16px;text-align:center;
      border:1px solid #dce8f0}
  .sc .num{font-size:2em;font-weight:700;color:#0a1730}
  .sc .lbl2{font-size:.78em;color:#7a9cc0;text-transform:uppercase;margin-top:4px}
  .pills{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:24px}
  .pill{padding:3px 10px;border-radius:20px;font-size:.8em;font-weight:600}
  .pg{background:#d4f5ef;color:#0a6b5e}.pb{background:#d0eaff;color:#0040a0}
  h3{color:#0a1730;margin:20px 0 8px;font-size:1em;font-weight:700}
  table{border-collapse:collapse;width:100%;font-size:.84em;margin-bottom:28px}
  th{background:#0a1730;color:#eaf1ff;padding:9px 8px;text-align:left}
  td{padding:8px;border-bottom:1px solid #eef2f7}
  tr:nth-child(even) td{background:#f8fafc}
  .p{color:#1fb7ac;font-weight:700}.f{color:#e74c3c;font-weight:700}
  .footer{border-top:1px solid #dce8f0;padding-top:14px;margin-top:28px;
          font-size:.76em;color:#aaa;display:flex;justify-content:space-between}
</style></head><body><div class="page">

<div class="header">
  <div>
    <div class="brand">Pay<span>con</span> · e2ePS</div>
    <div class="report-title">JIT Integration Certification Report</div>
  </div>
  <div style="font-size:2.2em">&#127970;</div>
</div>

{% set certified = certify_result.get('certified', False) if certify_result is defined else certified %}
<div class="verdict {{ 'cert-yes' if certified else 'cert-no' }}">
  {{ '&#9989;  CERTIFIED' if certified else '&#10060;  NOT CERTIFIED' }}
  &nbsp;&mdash;&nbsp; Score: {{ coverage.score }}% &nbsp;(threshold: {{ threshold }}%)
</div>

<div class="meta-grid">
  <div><div class="lbl">SUT Name</div>
       <div class="val">{{ sut.name if sut else '&mdash;' }}</div></div>
  <div><div class="lbl">API URL</div>
       <div class="val">{{ sut.api_url if sut else '&mdash;' }}</div></div>
  <div><div class="lbl">Customer JIT URL</div>
       <div class="val">{{ sut.customer_jit_url if sut else '&mdash;' }}</div></div>
  <div><div class="lbl">Run Timestamp</div>
       <div class="val">{{ timestamp }}</div></div>
</div>

<div class="scorecard">
  <div class="sc"><div class="num" style="color:{{ '#28a745' if certified else '#dc3545' }}">{{ coverage.score }}%</div>
                  <div class="lbl2">Score</div></div>
  <div class="sc"><div class="num">{{ coverage.passed_scenarios }}</div>
                  <div class="lbl2">Passed</div></div>
  <div class="sc"><div class="num">{{ coverage.total_scenarios - coverage.passed_scenarios }}</div>
                  <div class="lbl2">Failed</div></div>
  <div class="sc"><div class="num">{{ coverage.total_scenarios }}</div>
                  <div class="lbl2">Total</div></div>
</div>

<h3>Lifecycle Events Covered</h3>
<div class="pills">
  {% for evt in coverage.lifecycle_events_covered %}
  <span class="pill pg">{{ evt }}</span>
  {% else %}<span style="color:#aaa;font-size:.85em">None passed</span>
  {% endfor %}
</div>

<h3>Response Codes Covered</h3>
<div class="pills">
  {% for rc in coverage.rc_codes_covered %}
  <span class="pill pb">RC {{ rc }}</span>
  {% else %}<span style="color:#aaa;font-size:.85em">None passed</span>
  {% endfor %}
</div>

<h3>Per-Scenario Results</h3>
<table>
  <tr><th>Result</th><th>Scenario</th><th>Event</th>
      <th>Exp RC</th><th>Act RC</th>
      <th>Exp Decision</th><th>Act Decision</th><th>ms</th></tr>
  {% for r in results %}
  <tr>
    <td class="{{ 'p' if r.passed else 'f' }}">{{ '&#9989; PASS' if r.passed else '&#10060; FAIL' }}</td>
    <td>{{ r.name }}</td>
    <td>{{ r.event_type }}</td>
    <td>{{ r.expected_rc or '&mdash;' }}</td>
    <td>{{ r.actual_rc or '&mdash;' }}</td>
    <td>{{ r.expected_decision or '&mdash;' }}</td>
    <td>{{ r.actual_decision or '&mdash;' }}</td>
    <td>{{ '%.0f' % (r.duration_ms or 0) }}</td>
  </tr>
  {% endfor %}
</table>

<div class="footer">
  <span>Generated by Paycon e2ePS</span>
  <span>{{ timestamp[:10] }}</span>
</div>
</div></body></html>"""

    return Environment().from_string(template_str).render(**certify_result)


def build_certification_pdf(certify_result: dict):
    """Render the certification report as PDF bytes.

    Tries weasyprint first, then playwright headless chromium.
    Falls back to returning HTML bytes if neither is available.

    Returns:
        (bytes, mime_type) — caller uses mime_type to set Content-Type.
    """
    html = build_certification_report(certify_result)

    try:
        from weasyprint import HTML as WeasyHTML  # type: ignore
        return WeasyHTML(string=html).write_pdf(), "application/pdf"
    except (ImportError, Exception):
        pass

    try:
        from playwright.sync_api import sync_playwright  # type: ignore
        with sync_playwright() as p:
            browser = p.chromium.launch()
            pg = browser.new_page()
            pg.set_content(html, wait_until="networkidle")
            pdf = pg.pdf(format="A4", margin={"top": "20mm", "bottom": "20mm",
                                               "left": "15mm", "right": "15mm"})
            browser.close()
        return pdf, "application/pdf"
    except (ImportError, Exception):
        pass

    # Fallback: return HTML
    return html.encode("utf-8"), "text/html"


def _esc(s: str) -> str:
    """Minimal XML character escaping."""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
